'<form class="form" role="form">',
				      	'<div class="form-group">',
				        '<input type="email" class="form-control" placeholder="Email address" required="" autofocus="">',
				        '</div>',
				        '<div class="form-group">',
				        '<textarea rows="4" cols="50" class="form-control" placeholder="Comments" required=""></textarea>',
				        '</div>',
				        '<button class="btn btn-success pull-right" type="submit">Submit</button>',
				      '</form>',